# CodeSandbox supports debian and ubuntu based images
FROM debian:bullseye


# CodeSandbox supports debian and ubuntu based images
FROM debian:bullseye



# CodeSandbox supports debian and ubuntu based images
FROM debian:bullseye

